# Spring
spring:
  application:
    name: zuul

# Eureka configuration
ribbon:
  eureka:
    enabled: false

# Server
server:
  port: 8080

# Zuul routing
zuul:
  routes:
    app_1:
      url: http://localhost:3000
    app_2:
      url: http://localhost:3010

